### PR TITLE
[BUILD][DEPENDS] Upstream Depends Update

### PR DESCRIPTION
**Pull request by 2a5A1Ghu1**
This updates ohmcoins build system to PIVX's pre-sapling.
https://github.com/PIVX-Project/PIVX/tree/f1ee8fb87d181e51fb9a58a698d70652d055e34a

TODO:
(Upstream) Drop bip 70. This will allow dropping of protobuf and with some rework of other consensus code openssl(replaced by secp256k1).

Note: Only the big 3 OS's(macOS, Windows, Linux) and x86/arm have been tested for cross compile. RISC has not been tested as of yet but should build.

### CODE REVIEW

**Review by SeqSEE — COMMENTED** [review]
I've reviewed the changed files, looks good.

Going to test compiling it.

**Comment by 2a5A1Ghu1** [comment]
> I've reviewed the changed files, looks good.
> 
> Going to test compiling it.

Well yeah you grilled me about them on discord :stuck_out_tongue_winking_eye:

**Comment by 2a5A1Ghu1** [comment]
Windows cross compile docs resurrected

**Comment by 2a5A1Ghu1** [comment]
This is currently bombing when making a portable linux ohmcoin-qt binary and should not be merged until fixed.

**Comment by 2a5A1Ghu1** [comment]
Closing this for now as this requires far more upstream updates to the codebase than previously realized. I got a little ahead of myself here.

**Pull request closed without merging**
